name = "biolith-news"
main = "src/worker.ts"
compatibility_date = "2025-08-15"

[[kv_namespaces]]
binding = "NEWS_KV"
id = "db633c682a8942e086a191e14437b835"
preview_id = "2edf9a799ae34626ba4d63242ee19dc4"

[triggers]
crons = ["0 * * * *"]

[vars]
ALLOWED_ORIGIN = "https://biolith.org"

[ai]
binding = "AI"